# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3fba892d5af1c92a15d8e6b557034403"
name = "flax-app-test"
handle = "flax-app-test"
application_url = "https://microphone-carter-wants-buy.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "flaxlabsteststore.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://microphone-carter-wants-buy.trycloudflare.com/auth/callback",
  "https://microphone-carter-wants-buy.trycloudflare.com/auth/shopify/callback",
  "https://microphone-carter-wants-buy.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
